// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.Data.Entities;

namespace Project.Data.Migrations
{
    [DbContext(typeof(CobraKaiDbContext))]
    partial class CobraKaiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Project.Data.Entities.Journal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("JournalEntry");

                    b.Property<int?>("PersonId");

                    b.Property<int?>("SongId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("SongId");

                    b.ToTable("Journals");
                });

            modelBuilder.Entity("Project.Data.Entities.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email");

                    b.Property<string>("Firstname");

                    b.Property<string>("Lastname");

                    b.Property<string>("Password");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("Project.Data.Entities.Playlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("PersonId");

                    b.Property<int?>("SongId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("SongId");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("Project.Data.Entities.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Artist");

                    b.Property<string>("FilePath");

                    b.Property<string>("Genre");

                    b.Property<string>("Length");

                    b.Property<string>("ReleaseDate");

                    b.Property<decimal>("Size");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("Project.Data.Entities.Journal", b =>
                {
                    b.HasOne("Project.Data.Entities.Person", "Person")
                        .WithMany("Journal")
                        .HasForeignKey("PersonId");

                    b.HasOne("Project.Data.Entities.Song", "Song")
                        .WithMany("Journals")
                        .HasForeignKey("SongId");
                });

            modelBuilder.Entity("Project.Data.Entities.Playlist", b =>
                {
                    b.HasOne("Project.Data.Entities.Person", "Person")
                        .WithMany("Playlist")
                        .HasForeignKey("PersonId");

                    b.HasOne("Project.Data.Entities.Song", "Song")
                        .WithMany("Playlists")
                        .HasForeignKey("SongId");
                });
#pragma warning restore 612, 618
        }
    }
}
